// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqgnzxhqlbtpirrzsyde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZ256eGhxbGJ0cGlycnpzeWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTI4NzUsImV4cCI6MjA2Njc2ODg3NX0.cXcIsOsyTBlLcxMnG56YXdaEgvikGkNwjBOQFeAStGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);